baseURL = 'http://www.quarteera.de'
languageCode = 'ru-RU'
title = 'Quarteera /// Russian Queer in Germany'
defaultContentLanguage = 'ru'
[languages]
  [languages.ru]
    title = 'Русскоязычные ЛГБТ в Германии '
    languageName = 'RU'
    weight = 1
    contentDir = 'content/ru'
    [languages.ru.menu]
    [[languages.ru.menu.main]]
      name = 'О нас'
      url = '/about'
      weight = 0
      pre = 'yellow'
      identifier = 'about'
    [[languages.ru.menu.main]]
      name = 'Проекты'
      url = '/projects'
      weight = 1
      pre = 'green'
      identifier = 'projects'
    [[languages.ru.menu.main]]
      name = 'Миграция'
      url = '/migration'
      weight = 2
      pre = 'red'
      identifier = 'migration'
    [[languages.ru.menu.main]]
      name = 'Поддержать'
      url = '/help'
      weight = 3
      pre = 'purple'
      identifier = 'help'
    [[languages.ru.menu.footer]]
      name = 'Пресса'
      url = '/press'
      weight = 1
    [[languages.ru.menu.footer]]
      name = 'Карьера'
      url = '/karriere'
      weight = 2
    [[languages.ru.menu.footer]]
      name = 'Выходные данные'
      url = '/impressum'
      weight = 3
    [[languages.ru.menu.footer]]
      name = 'Политика конфеденциальности'
      url = '/datenschutz'
      weight = 4
  [languages.de]
    title = 'Russischsprachige LGBT in Deutschland'
    languageName = 'DE'
    weight = 2
    contentDir = 'content/de'
    [languages.de.menu]
    [[languages.de.menu.main]]
      name = 'Über uns'
      url = '/about'
      weight = 0
      pre = 'yellow'
      identifier = 'about'
    [[languages.de.menu.main]]
      name = 'Projekte'
      url = '/projects'
      weight = 1
      pre = 'green'
      identifier = 'projects'
    [[languages.de.menu.main]]
      name = 'Migration'
      url = '/migration'
      weight = 2
      pre = 'red'
      identifier = 'migration'
    [[languages.de.menu.main]]
      name = 'Mitmachen'
      url = '/help'
      weight = 3
      pre = 'purple'
      identifier = 'help'
    [[languages.de.menu.footer]]
      name = 'Press'
      url = '/de/press'
      weight = 1
    [[languages.de.menu.footer]]
      name = 'Karriere'
      url = '/de/karriere'
      weight = 2
    [[languages.de.menu.footer]]
      name = 'Impressum'
      url = '/impressum'
      weight = 3
    [[languages.de.menu.footer]]
      name = 'Datenschutz'
      url = '/datenschutz'
      weight = 4
